grails-app/domain/getitdone/User.groovy
package getitdone

class User {

    Date dateCreated
    Date lastUpdated

    String firstName
    String lastName
    String middleName
    String email

    static hasMany = [tasks: Task, workLogs: Work]

    static constraints = {
        firstName nullable: true
        lastName nullable: true
        middleName nullable: true
        email blank: false, unique: true, email: true
    }


}

grails-app/controllers/getitdone/UserController.groovy
package getitdone

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class UserController {

    UserService userService
    TaskService taskService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond userService.list(params), model:[userCount: userService.count()]
    }

    def show(Long id) {
        respond userService.get(id)
    }

    def create() {
        respond new User(params)
    }

    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    def edit(Long id) {
        User user = userService.get(id)
        respond user, model: [userTaskCount: taskService.countByAssignee(user)]
    }

    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        userService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                %{--<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-user" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.user}" method="POST">
                <fieldset class="form">
                    <f:all bean="user"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                %{--<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-user" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.user}" method="PUT">
                <g:hiddenField name="version" value="${this.user?.version}" />
                <fieldset class="form">
                    %{--<f:all bean="user"/>--}%

                    <div class="fieldcontain">
                        <label for="firstName">First Name</label>
                        <g:field type="text" id="firstName" name="firstName" value="${this.user.firstName}"/>
                    </div>
                    <div class="fieldcontain">
                        <label for="middleName">Middle Name</label>
                        <g:field type="text" id="middleName" name="middleName" value="${this.user.middleName}"/>
                    </div>
                    <div class="fieldcontain">
                        <label for="lastName">Last Name</label>
                        <g:field type="text" id="lastName" name="lastName" value="${this.user.lastName}"/>
                    </div>
                    <div class="fieldcontain required">
                        <label for="email">
                            Email
                            <span class="required-indicator">*</span>
                        </label>
                        <g:field type="text" id="email" name="email" value="${this.user.email}"/>
                    </div>

                    <div class="fieldcontain">
                        <label>
                            Assigned Tasks Count
                        </label>
                        <span class="badge">
                            ${this.userTaskCount}
                        </span>
                    </div>

                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                %{--<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-user" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${userList}" properties="['email', 'firstName', 'lastName', 'middleName', 'dateCreated', 'lastUpdated']"/>

            %{--<table>--}%
                %{--<thead>--}%
                %{--<tr>--}%
                    %{--<g:each in="${domainProperties}" var="p" status="i">--}%
                        %{--<g:sortableColumn property="${p.property}" title="${p.label}" />--}%
                    %{--</g:each>--}%
                %{--</tr>--}%
                %{--</thead>--}%
                %{--<tbody>--}%
                %{--<g:each in="${userList}" var="bean" status="i">--}%
                    %{--<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">--}%
                        %{----}%
                        %{----}%
                        %{--<g:each in="${domainProperties}" var="p" status="j">--}%
                            %{--<g:if test="${j==0}">--}%
                                %{--<td><g:link method="GET" resource="${bean}"><f:display bean="${bean}" property="${p.property}" displayStyle="${displayStyle?:'table'}" theme="${theme}"/></g:link></td>--}%
                            %{--</g:if>--}%
                            %{--<g:else>--}%
                                %{--<td><f:display bean="${bean}" property="${p.property}"  displayStyle="${displayStyle?:'table'}" theme="${theme}"/></td>--}%
                            %{--</g:else>--}%
                        %{--</g:each>--}%
                    %{--</tr>--}%
                %{--</g:each>--}%
                %{--</tbody>--}%
            %{--</table>--}%

            <div class="pagination">
                <g:paginate total="${userCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/user/show.gsp
<%@ page import="getitdone.Task" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                %{--<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-user" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            %{--<f:display bean="user" />--}%

            <ol class="property-list user">
                <li class="fieldcontain">
                    <span id="firstName-label" class="property-label">First Name</span>
                    <div class="property-value" aria-labelledby="firstName-label">
                        <f:display bean="${this.user}" property="firstName"  displayStyle="table" theme="${theme}"/>
                    </div>
                </li>
                <g:if test="${this.user.middleName}">
                <li class="fieldcontain">
                    <span id="middleName-label" class="property-label">Middle Name</span>
                    <div class="property-value" aria-labelledby="middleName-label">
                        <f:display bean="${this.user}" property="middleName"  displayStyle="table" theme="${theme}"/>
                    </div>
                </li>
                </g:if>
                <li class="fieldcontain">
                    <span id="lastName-label" class="property-label">Last Name</span>
                    <div class="property-value" aria-labelledby="lastName-label">
                        <f:display bean="${this.user}" property="lastName"  displayStyle="table" theme="${theme}"/>
                    </div>
                </li>
                <li class="fieldcontain">
                    <span id="email-label" class="property-label">Email</span>
                    <div class="property-value" aria-labelledby="email-label">
                        <f:display bean="${this.user}" property="email"  displayStyle="table" theme="${theme}"/>
                    </div>
                </li>
                <li class="fieldcontain">
                    <span id="tasks-label" class="property-label">Assigned Tasks</span>
                    <div class="property-value" aria-labelledby="tasks-label">
                        <ul class="list-unstyled">
                            <g:each in="${this.user.tasks.findAll {
                                it.status != Task.TASK_STATUS_COMPLETED && it.status != Task.TASK_STATUS_ABORTED
                            }.sort {it.lastUpdated ?: it.dateCreated}.reverse()}" var="task" status="j">
                                <li class="task-description">
                                    <div>
                                    <g:link style="text-decoration: none" method="GET" controller="task" action="show" params="[id: task.id]">
                                        ${task.description.encodeAsRaw()}
                                    </g:link>
                                    <span class="badge ${task.status == 'created' ? 'badge-info' : 'badge-primary'}">
                                    ${task.status}
                                    </span> at ${task.lastUpdated ?: task.dateCreated}
                                    </div>
                                </li>
                            </g:each>
                        </ul>
                    </div>
                </li>
                <li class="fieldcontain">
                    <span id="ended-tasks-label" class="property-label">Ended Tasks</span>
                    <div class="property-value" aria-labelledby="ended-tasks-label">
                        <ul class="list-unstyled">
                            <g:each in="${this.user.tasks.findAll {
                                it.status == Task.TASK_STATUS_COMPLETED || it.status == Task.TASK_STATUS_ABORTED
                            }.sort {it.lastUpdated ?: it.dateCreated}.reverse()}" var="task" status="k">
                                <li class="task-description">
                                    <div>
                                    <g:link method="GET" controller="task" action="show" params="[id: task.id]">
                                        ${task.description.encodeAsRaw()}
                                    </g:link>
                                    <span class="badge ${task.status == 'completed' ? 'badge-success' : 'badge-warning'}">
                                        ${task.status}
                                    </span> at ${task.lastUpdated ?: task.dateCreated}
                                    </div>
                                </li>
                            </g:each>
                        </ul>
                    </div>
                </li>
            </ol>

            <g:form resource="${this.user}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.user}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>