grails-app/controllers/getitdone/EmailSendController.groovy
package getitdone

/**
 * a simple web ui to compose and send email, using Grails email plugin.
 * the web ui is using CK-Edit to support html email body.
 * ref url: https://www.djamware.com/post/58b50fee80aca736bb5e4369/grails-3-send-email-example
 */
class EmailSendController {

    def index() {
    }

    def send() {
        sendMail {
            to params.address
            subject params.subject
//            text params.body
            html params.body  // use CKEditor to edit html body for email body
        }

        flash.message = "Message sent at ${new Date()}"
        redirect action:"index"
    }

}

grails-app/views/emailSend/index.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Email Sender</title>

    <asset:link rel="icon" href="favicon.ico" type="image/x-ico" />

    <script src="//cdn.ckeditor.com/4.6.0/full-all/ckeditor.js"></script>

</head>
<body>
<div id="content" role="main">
    <section class="row colset-2-its">
        <g:if test="${flash.message}">
            <div class="message" role="alert">
                ${flash.message}
            </div>
        </g:if>
        <h2>Email Sender Form</h2>
        <g:form controller="emailSend" action="send">
            <div class="fieldcontain">
                <g:textField name="address" placeholder="youremail@domain.com" required="" />
            </div>
            <div class="fieldcontain">
                <g:textField name="subject" placeholder="Your Subject" required="" />
            </div>
            <div class="fieldcontain">
                <g:textArea name="body" rows="5" cols="80" placeholder="Your message" required="" />
            </div>
            <fieldset>
                <g:submitButton name="send" value="Send" />
            </fieldset>
        </g:form>
    </section>
</div>


<script>
    CKEDITOR.replace('body', {
        extraPlugins: 'codesnippet'
    });
</script>

</body>
</html>