grails-app/domain/getitdone/Task.groovy
package getitdone

/**
 * Task domain represents the unit of work. It consists of zero, one, or more {@link Work} logs.
 * @see {@link Work}
 */
class Task {

    public static final String TASK_STATUS_STARTED = 'started'
    public static final String TASK_STATUS_CREATED = 'created'
    public static final String TASK_STATUS_COMPLETED = 'completed'
    public static final String TASK_STATUS_ABORTED = 'aborted'
//    public static final String TASK_STATUS_BLOCKED = 'blocked'
    public static final List LIST_TASK_STATUS = [TASK_STATUS_STARTED, TASK_STATUS_CREATED, TASK_STATUS_COMPLETED, TASK_STATUS_ABORTED]

    Date dateCreated
    Date lastUpdated

    String description

    String status //todo: add index on this column in BootStrap.groovy

//    User creator  //todo: might be needed when task lifecycle is tracked
    User assignee

    static hasMany = [workLogs: Work, comments: Comment]

    static constraints = {
        description blank: false, maxSize: 2048

        assignee nullable: true  // a task can be un-assigned

        status blank: false, inList: LIST_TASK_STATUS
    }

    //fixme: for unknown reason, beforeInsert is not invoked before persistence, so beforeValidate is used here
    def beforeValidate() {
        if (!status) {
            status = TASK_STATUS_CREATED
        }
    }
}

grails-app/domain/getitdone/User.groovy
package getitdone

class User {

    Date dateCreated
    Date lastUpdated

    String firstName
    String lastName
    String middleName
    String email

    static hasMany = [tasks: Task, workLogs: Work]

    static constraints = {
        firstName nullable: true
        lastName nullable: true
        middleName nullable: true
        email blank: false, unique: true, email: true
    }


}

grails-app/controllers/getitdone/TaskController.groovy
package getitdone

import grails.events.EventPublisher
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class TaskController implements EventPublisher {

    TaskService taskService
    TaskDataService taskDataService
    UserService userService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        // apply default sorting
        if (!params.sort) {
            params.sort = 'lastUpdated'
            params.order = 'desc'
        }
        // taskService.listWithAssignee() vs taskCrudService.listWithAssignee() to show N+1 case
//        respond taskService.listWithAssignee(params), model:[taskCount: taskService.count()]
        respond taskDataService.listWithAssignee(params), model:[taskCount: taskService.count()]
    }

    def show(Long id) {
        respond taskService.get(id)
    }

    def create() {
        respond new Task(params), model: [userList: userService.list()]
    }

    def save(Task task) {
        if (task == null) {
            notFound()
            return
        }

        try {
            taskService.save(task)
        } catch (ValidationException e) {
            respond task.errors, view:'create', model: [userList: userService.list()]
            return
        }

        // at this point task has been successfully assigned
        notify("eventTaskAssigned", [task: task, assignee: task.assignee,
                taskUrl: g.createLink(controller: 'task', action: 'show', id: task.id, absolute: true).encodeAsHTML()
        ])

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'task.label', default: 'Task'), task.id])
                redirect task
            }
            '*' { respond task, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond taskService.get(id), model: [userList: userService.list()]
    }

    def update(Task task) {
        if (task == null) {
            notFound()
            return
        }

        try {
            taskService.save(task)
        } catch (ValidationException e) {
            respond task.errors, view:'edit', model: [userList: userService.list()]
            return
        }

        // at this point task has been successfully updated
        // notify assignee if this update contains an assignment
        if (task.status != Task.TASK_STATUS_ABORTED && task.status != Task.TASK_STATUS_COMPLETED) {
            notify("eventTaskAssigned", [task: task, assignee: task.assignee,
                                         taskUrl: g.createLink(controller: 'task', action: 'show', id: task.id, absolute: true).encodeAsHTML()
            ])
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'task.label', default: 'Task'), task.id])
                redirect task
            }
            '*'{ respond task, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        taskService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'task.label', default: 'Task'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'task.label', default: 'Task'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/task/_quilljs_integration.gsp
<!-- Include the Quill library -->
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<!-- Initialize Quill editor -->
<script>
    var quill = new Quill('#editor-container', {
        modules: {
            toolbar: [
                [{ size: [ 'small', false, 'large', 'huge' ]}],
                ['bold', 'italic'],
                ['link', 'blockquote', 'code-block', 'image'],
                [{ list: 'ordered' }, { list: 'bullet' }]
            ]
        },
        placeholder: 'Compose a task description...',
        theme: 'snow'
    });

    var form = document.querySelector('form');
    form.onsubmit = function() {
        var desc = document.querySelector('input[name=description]');
        // desc.value = JSON.stringify(quill.getContents()); // getting Delta format content
        // console.log("Submitted", $(form).serialize(), $(form).serializeArray());

        var descHtml = quill.root.innerHTML;  // getting html format content
        desc.value = descHtml;
        console.log("html content:", descHtml);

        // return false;  // abort real form submission
        return true;
    };
</script>

grails-app/views/task/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'task.label', default: 'Task')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-task" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                %{--<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-task" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.task}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.task}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.task}" method="POST">
                <fieldset class="form">
                    <div class="fieldcontain required">
                        <label for="description">
                            Description
                            <span class="required-indicator">*</span>
                        </label>
                        %{--<g:textArea id="description" name="description" rows="3" placeholder="task description" required=""--}%
                                    %{--maxlength="2048"/>--}%

                        <!-- Include stylesheet for QuillJS editor -->
                        <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
                        <!-- Create the editor container -->
                        <input type="hidden" id="description" name="description" />
                        <div id="editor-container">
                        </div>
                    </div>
                    <div class="fieldcontain">
                        <label for="assignee">
                            Assignee
                        </label>
                        <g:select name="assignee.id" id="assignee" from="${this.userList}"
                                  optionKey="id" optionValue="email"
                                  noSelection="['':'Assign task to:']"/>
                    </div>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>

        <g:render template="quilljs_integration" />
    </body>
</html>

grails-app/views/task/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'task.label', default: 'Task')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-task" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                %{--<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-task" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.task}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.task}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.task}" method="PUT">
                <g:hiddenField name="version" value="${this.task?.version}" />
                <fieldset class="form">
                    <div class="fieldcontain required">
                        <label for="description">
                            Description
                            <span class="required-indicator">*</span>
                        </label>
                        %{--<g:textArea id="description" name="description" rows="3" placeholder="task description" required=""--}%
                                    %{--maxlength="2048" value="${this.task.description}" />--}%
                        %{-- Use QuillJS rich text editor for description --}%
                        <!-- Include stylesheet for QuillJS editor -->
                        <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
                        <!-- Create the editor container -->
                        <input type="hidden" id="description" name="description" value="${this.task.description}" />
                        <div id="editor-container">
                            ${this.task.description.encodeAsRaw()}
                        </div>
                    </div>
                    <div class="fieldcontain">
                        <label for="assignee">
                            Assignee
                        </label>
                        <g:select name="assignee.id" id="assignee" from="${this.userList}"
                                  optionKey="id" optionValue="email"
                                  value="${this.task.assigneeId}"
                                  noSelection="['':'Assign task to:']"/>
                    </div>
                    <div class="fieldcontain required">
                        <label for="status">
                            Status
                            <span class="required-indicator">*</span>
                        </label>
                        %{--<g:field type="text" id="status" name="status" required="" value="${this.task.status}"/>--}%
                        <g:select name="status" from="${getitdone.Task.LIST_TASK_STATUS}" value="${this.task.status}" />
                    </div>

                    %{--<f:all bean="task"/>--}%
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>

        <g:render template="quilljs_integration" />
    </body>
</html>

grails-app/views/task/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'task.label', default: 'Task')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-task" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                %{--<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-task" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            %{--<f:table collection="${taskList}" />--}%
            <table>
                <thead>
                <tr>
                    <g:sortableColumn property="description" title="Description" />
                    <th>Assignee</th>
                    <g:sortableColumn property="status" title="Status" />
                    <g:sortableColumn property="dateCreated" title="Last Update Time" />
                    %{--<g:sortableColumn property="dateCreated" title="Create Time" />--}%
                </tr>
                </thead>
                <tbody>
                <g:each in="${taskList}" var="bean" status="i">
                    <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                        <td class="task-description">
                            <g:link style="text-decoration: none;" method="GET" resource="${bean}">${bean.description.encodeAsRaw()}</g:link>
                        </td>
                        <td>
                            <g:link method="GET" controller="user" action="show" params="[id: bean.assigneeId]">
                                <f:display bean="${bean}" property="assignee.email"  displayStyle="table" theme="${theme}"/>
                            </g:link>
                        </td>
                        <td><f:display bean="${bean}" property="status"  displayStyle="table" theme="${theme}"/></td>
                        <td><f:display bean="${bean}" property="lastUpdated"  displayStyle="table" theme="${theme}"/></td>
                        %{--<td><f:display bean="${bean}" property="dateCreated"  displayStyle="table" theme="${theme}"/></td>--}%
                    </tr>
                </g:each>
                </tbody>
            </table>

            <div class="pagination">
                <g:paginate total="${taskCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/task/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'task.label', default: 'Task')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-task" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                %{--<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>--}%
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-task" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <ol class="property-list task">
                <li class="fieldcontain">
                    <span id="descriptoin-label" class="property-label">Description</span>
                    <div class="property-value" aria-labelledby="description-label">
                        ${this.task.description.encodeAsRaw()}
                    </div>
                </li>
                <li class="fieldcontain">
                    <span id="assignee-label" class="property-label">Assignee</span>
                    <div class="property-value" aria-labelledby="assignee-label">
                        %{-- a task may not be assigned thus assigneeId could be null --}%
                        <g:if test="${this.task.assigneeId}">
                        <g:link controller="user" action="show" id="${this.task.assigneeId}">
                        ${this.task.assignee.email}
                        </g:link>
                        </g:if>
                    </div>
                </li>
                <li class="fieldcontain">
                    <span id="status-label" class="property-label">Status</span>
                    <div class="property-value" aria-labelledby="status-label">
                        ${this.task.status}
                    </div>
                </li>
                <li class="fieldcontain">
                    <div class="property-value" style="display: flex; align-items: center;">
                        <span style="flex-grow: 1;
                        border-bottom: 1px solid #CCCCCC;
                        margin: 5px"></span>
                    </div>

                </li>
                <li class="fieldcontain">
                    <span id="work-label" class="property-label">Work Logs</span>
                    <div class="property-value" aria-labelledby="work-label">
                        <ul class="list-unstyled">
                            <g:each in="${this.task.workLogs.sort {it.lastUpdated ?: it.dateCreated}.reverse()}" var="work" status="j">
                                <li>
                                    <g:link method="GET" controller="work" action="show" params="[id: work.id]">
                                        ${work.timeSpent} ${work.timeSpentUnit}
                                    </g:link>
                                    [on ${work.workDate.format('yyyy-MM-dd')} by ${work.worker.email}]
                                </li>
                            </g:each>
                        </ul>
                    </div>
                </li>

                <li class="fieldcontain">
                    <span id="comments-label" class="property-label">Comments</span>
                    <div class="property-value" aria-labelledby="comments-label">
                        <ul class="list-unstyled">
                            <g:if test="${this.task.comments}">
                                <g:each in="${this.task.comments.sort {it.lastUpdated}}" var="comment" status="k">
                                    <li>
                                        <div class="card card-block">
                                            <div class="card-title">
                                                Commented at ${comment.dateCreated.format('yyyy-MM-dd HH:mm:ss')}
                                            </div>
                                            <div class="card-text">
                                                %{--<h5 class="card-title">Special title treatment</h5>--}%
                                                ${comment.content.encodeAsRaw()}
                                                %{--<a href="#" class="btn btn-primary">Go somewhere</a>--}%
                                            </div>
                                        </div>
                                    </li>
                                </g:each>
                            </g:if>
                            <g:else>
                                <li>
                                    <div class="card card-block">
                                        <div class="card-title">
                                            There's no comment for this task. Add one below.
                                        </div>
                                    </div>

                                </li>
                            </g:else>
                            <li>
                                %{-- insert inline comment editor --}%
                                <g:form name="form-comment" controller="comment" action="save" method="POST">
                                        <!-- Include stylesheet for QuillJS editor -->
                                        <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

                                        <input type="hidden" id="task.id" name="task.id" value="${this.task.id}" />
                                        <input type="hidden" id="comment-content" name="content" />
                                        <input type="hidden" id="form-redirect-url" name="redirect.url"
                                                value="${g.link(controller: 'task', action: 'show', id: this.task.id)}" />

                                        <!-- Create the editor container -->
                                        <div id="editor-container">
                                        </div>
                                    <div>
                                        <g:submitButton name="create" class="btn-default save" value="Submit Comment" />
                                    </div>

                                </g:form>
                            </li>
                        </ul>
                    </div>
                </li>
            </ol>
            <g:form resource="${this.task}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.task}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                    <g:link class="edit" controller="work"  action="create" params="['task.id': this.task.id, 'worker.id': this.task.assigneeId]">
                        <g:message code="default.button.logWork.label" default="Log Work" />
                    </g:link>
                </fieldset>
            </g:form>
        </div>

    <!-- Include the Quill library -->
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <asset:javascript src="quill-image-resize.min.js" />

    <!-- Initialize Quill editor -->
    <script>

        Quill.register('modules/imageResize', ImageResize);


        var quill = new Quill('#editor-container', {
            modules: {
                toolbar: [
                    [{ size: [ 'small', false, 'large', 'huge' ]}],
                    // [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
                    // [{ 'script': 'sub' }, { 'script': 'super' }],  // superscript/subscript
                    [{ 'color': [] }, { 'background': [] }],    // dropdown with defaults from theme
                    [{ 'font': [] }],
                    [{ 'align': [] }],
                    ['bold', 'italic'],
                    ['link', 'blockquote', 'code-block', 'image'],
                    [{ list: 'ordered' }, { list: 'bullet' }]
                ],
                //fixme: this gets 'moduleClass is not a constructor' error
                // imageResize: {}
            },
            placeholder: 'Compose comment ...',
            theme: 'snow'
        });



        var form = document.querySelector('form[name=form-comment]');
        form.onsubmit = function() {
            var ctnt = document.querySelector('input[name=content]');

            var ctntHtml = quill.root.innerHTML;  // getting html format content
            ctnt.value = ctntHtml;
            console.log("html content:", ctntHtml);

            // return false;  // abort real form submission
            return true;
        };
    </script>

    </body>
</html>